P2GNoF40.R ROCKE-3D

P2GNoF40: ROCKE-3D, based on ModelE 2.1 with very minor updates and fixes
  P2: planet_2.0 model version
  G: GISS radiation
  N: atmospheric composition for Earth, year 1850, without aerosols, O3, O2,
     and stratospheric H2O formation from CH4 oxidation
  o: dynamic 1x1.25 horizontal resolution with 40 layer ocean
  F40: 2x2.5 horizontal resolution with 40 layer atmosphere
       Model top at 0.1 mb (+3 radiation-only layers above)
Uses turbulence scheme, no gravity wave drag
Time steps: dynamics 7.5 min leap frog
            physics 30 min.
            radiation 2.5 hrs (NRAD=5)
Filters: U,V in E-W and N-S direction (after every physics time step)
         U,V in E-W direction near poles (after every dynamics time step)
         sea level pressure (after every physics time step)

Preprocessor Options
#define PLANET_PARAMS anoxicEarth
#define NEW_IO                   ! new I/O (netcdf) on
#define CHECK_OCEAN                  ! needed to compile aux/file CMPE002
!#define SIMPLE_MESODIFF           ! use either this line for present-day Earth,
#define CONSTANT_MESO_DIFFUSIVITY  ! or this one for non-Earth cases
#define ODIFF_TRIDIAG_CYCLIC       ! horizontal momentum mixing
#define OCN_LAYERING L40_5008m
#define ODIFF_FIXES_2017
#define EXPEL_COASTAL_ICEXS
#define CACHED_SUBDD
End Preprocessor Options

Object modules:
     ! resolution-specific source codes
Atm144x90                           ! horizontal resolution is 144x90 -> 2x2.5deg
AtmL40p                             ! vertical resolution
FFT144                              ! Fast Fourier Transform
ORES_1Qx1 OFFT288E                  ! ocean horiz res 1.25x1deg

IO_DRV                              ! new i/o

     ! GISS dynamics without gravity wave drag
ATMDYN MOMEN2ND                     ! atmospheric dynamics
QUS_DRV QUS3D                       ! advection of Q/tracers
STRAT_DUM

#include "latlon_source_files"
#include "planet_source_files"
#include "dynamic_ocn_source_files"
OCN_Int_LATLON                      ! atm-ocn regrid routines

SUBDD

Components:
#include "E4_components_nc"    /* without "Ent" */
Ent

Component Options:
OPTS_Ent = ONLINE=YES PS_MODEL=FBB PFT_MODEL=ENT /* needed for "Ent" only */
OPTS_dd2d = NC_IO=PNETCDF

Data input files:
#include "IC_144x90_input_files"
#include "dynamic_ocn_288x180_input_files_planet"
RVR=RD_Fd.nc             ! river direction file
NAMERVR=RD_Fd.names.txt  ! named river outlets

#include "land144x90_planet_input_files_nocrops"
#include "rad_input_files_planet_giss"

MSU_wts=MSU_SSU_RSS_weights.txt      ! MSU-diag
REG=REG2X2.5                      ! special regions-diag

Label and Namelist:  (next 2 lines)
P2GNoF40 (ROCKE-3D, based on P2GNoF40 template)

&&PARAMETERS
#include "dynamic_ocn_params_planet"
#include "sdragF40_params"

! cond_scheme=2   ! newer conductance scheme (N. Kiang) ! not used with Ent

! The following two lines are only used when aerosol/radiation interactions are off
FS8OPX=1.,1.,1.,1.,1.5,1.5,1.,1.
FT8OPX=1.,1.,1.,1.,1.,1.,1.3,1.

! Tuning parameters as of 2/2019
U00a=0.635  ! above 850mb w/o MC region;  tune this first to get 30-35% high clouds
U00b=1.50   ! below 850mb and MC regions; tune this last  to get rad.balance
WMU_multiplier = 1.
WMUI_multiplier = 0.001
radiusl_multiplier=1.16
radiusi_multiplier=1.
use_vmp=1

! Cloud inhomogeneity correction
KCLDEP=1    ! use a constant value for CLDEPS
EPSCON=0.12 ! use CLDEPS=0.12

! Stellar constant at 1 AU (default = 1360.67 W/m2)
!planet_s0=1360.67
! S0X has been removed and will have no effect on results

l_uniform_ghg=1 ! deactivates prescribed GHG distributions
O2X=0.
CO2X=1.
O3X=0. ! turn of O3, to turn on delete this line and add O3file
H2OstratX=1.
xCDpbl=1.
KSIALB=0        ! 6-band albedo (Hansen) (=-1 no land ice fixup, 1 Lacis' scheme)
wsn_max=2.   ! restrict snow depth to 2 m-h2o (if 0. snow depth is NOT restricted)

maxctop=0.       ! maximum level for cloud-top calculations (mb)
fOnOff=0.        ! =0. disables SW-H2O correction
PTLISO=0.        ! pressure(mb) above which radiation assumes isothermal layers
H2ObyCH4=0.      ! if =1. activates stratospheric H2O generated by CH4 without interactive chemistry
KSOLAR=2         ! 2: use long annual mean file ; 1: use short monthly file

#include "planet_atmCompos_1850_params_nocrops"

DTsrc=1800.      ! cannot be changed after a run has been started
DT=225.
! parameters that control the Shapiro filter
DT_XUfilter=225. ! Shapiro filter on U in E-W direction; usually same as DT
DT_XVfilter=225. ! Shapiro filter on V in E-W direction; usually same as DT
DT_YVfilter=0.   ! Shapiro filter on V in N-S direction
DT_YUfilter=0.   ! Shapiro filter on U in N-S direction

#include "EOT_defaults"

NIsurf=2         ! surface interaction computed NIsurf times per source time step
NRAD=5           ! radiation computed NRAD times per source time step
#include "planet_diag_params"

Nssw=2           ! until diurnal diags are fixed, Nssw has to be even
Ndisk=1440       ! write fort.1.nc or fort.2.nc every NDISK source time step
&&END_PARAMETERS

&INPUTZ
 YEARI=1949,MONTHI=12,DATEI=1,HOURI=0, ! pick IYEAR1=YEARI (default) or < YEARI
 YEARE=1949,MONTHE=12,DATEE=2,HOURE=0,     KDIAG=12*0,9,
 ISTART=2,IRANDI=0, YEARE=1949,MONTHE=12,DATEE=1,HOURE=1,
/
