PSTdustM40_Mars.R M40 Desert World with selected Mars-like parameters, inputs    M. Kelley 7/2013

Preprocessor Options
#define PLANET_PARAMS likeMars ! parameter set selector in shared/PlanetParams_mod.F90
#define NEW_IO
#define USE_PLANET_RAD
#define GISS_RAD_OFF
! on planet_1.0 there was some problem with land ice - check
! #define NO_LAND_ICE
#define DO_CO2_CONDENSATION
#define DO_CO2_CONDENSATION_APPLY
#define DO_CO2_CONDENSATION_DEBUG_SITES
!---> generic tracers code start
#define TRAC_ADV_CPU             ! timing index for tracer advection on
#define TRACERS_ON               ! include tracers code
#define TRACERS_WATER            ! wet deposition and water tracer
#define TRACERS_DRYDEP           ! default dry deposition
#define TRDIAG_WETDEPO           ! additional wet deposition diags for tracers
!---> OMA start
#define TRACERS_DUST             ! include dust tracers
#define TRACERS_DUST_Silt4       ! include 4th silt size class of dust
!<--- OMA end
#define CACHED_SUBDD
End Preprocessor Options

Object modules: (in order of decreasing priority)
     ! resolution-specific source codes
Atm72x46                   ! horizontal resolution is 72x46 -> 4x5deg
!AtmL20                     ! vertical resolution is 20 layers -> 0.1mb
AtmL40p
STRAT_DUM
FFT72                              ! Fast Fourier Transform
IO_DRV                             ! new i/o

     ! GISS dynamics w/o gravity wave drag
ATMDYN MOMEN2ND                     ! atmospheric dynamics
QUS_DRV QUS3D                       ! advection of Q/tracers

#include "latlon_source_files"
#include "modelE4_source_files"
#include "static_ocn_source_files"

#include "tracer_shared_source_files"
#include "tracer_dust_source_files"
TRDIAG                              ! new i/o
SUBDD

planet_rad planet_alb lw_control sw_control ! planet radiation source files

Components:
#include "E4_components_nc"    /* without "Ent" */
Ent
tracers
socrates

Component Options:
OPTS_Ent = ONLINE=YES PS_MODEL=FBB PFT_MODEL=ENT
OPTS_dd2d = NC_IO=PNETCDF

Data input files:

#include "IC_72x46_input_files_Mars"
#include "land_72x46_input_files_Mars"
#include "rad_72x46_input_files_Mars"
#include "dust_tracer_72x46_input_files_Mars"

Label and Namelist:
PSTdustM40_Mars (M40 Desert World with dust tracers and selected Mars-like parameters, inputs)

&&PARAMETERS

! Input files for planet radiation (SOCRATES)
solar_spec='sun'
spectral_file_lw='sp_lw_dsa_mars/sp_lw_17_dsa_mars'
spectral_file_sw='sp_sw_dsa_mars/sp_sw_42_dsa_mars'
aer_opt_prop_lw='sp_lw_dsa_mars/aer_lw_17_dsa_mars.nc'
aer_opt_prop_sw='sp_sw_dsa_mars/aer_sw_42_dsa_mars_sun.nc'
aer_opt_prop_diag='sp_diag/aer_diag_std.nc'

! calculate initial surface pressure for hydrostatic consistency with topography
initial_psurf_from_topo=1

! linear damping timescales (sec) for winds in the top 4 layers.
! These probably need to be tuned.  Change the number of values here
! to change the number of layers in which damping is applied.
rtau=20000.,15000.,10000.,5000.

! minimum and maximum allowed column mass (kg/m2) for error checking
mincolmass=0.
maxcolmass=500.

#include "orbital_params_Mars"
#include "stellar_params_Mars"
#include "static_ocn_params_Mars"
#include "atmos_gases_params_Mars"

! the model requires the following parameter to be set, though it
! does not affect Mars runs
master_yr=1850

! A dry planet will have no lakes, but we set this in case someone
! eventually decides to start with an initially wet soil.
variable_lk=1   ! variable lakes

! disable some Earth hacks
maxctop=0.       ! maximum level for cloud-top calculations (mb)
H2ObyCH4=0.     ! deactivates strat.H2O generated by CH4

#include "aerosol_OMA_params_Mars"
#include "dust_params_oma_Mars"

! Physics timestep (sec). Cannot be changed after a run has been started.
DTsrc=1850.

! Dynamics timestep.
! Note that DTsrc/DT should be an even integer.
DT=20.

! parameters that control the Shapiro filter
DT_XUfilter=20. ! Shapiro filter on U in E-W direction; usually same as DT
DT_XVfilter=20. ! Shapiro filter on V in E-W direction; usually same as DT
DT_YVfilter=0.   ! Shapiro filter on V in N-S direction
DT_YUfilter=0.   ! Shapiro filter on U in N-S direction

#include "EOT_defaults"

! Number of surface timesteps per physics timestep.  Probably does not
! need to be changed for M20 Mars.
NIsurf=2        ! increase as layer 1 gets thinner

! Number of physics timesteps per radiation timestep.  Default is 5.
nrad=1

#include "diag_params_Mars"

! save alternating checkpoint files every Ndisk physics timesteps
Ndisk=960

! KCOPY=1: save acc and alternating checkpoint files only.  KCOPY=2: save rsf also
KCOPY=2

! restart state is saveable every nssw timesteps.
nssw=2          ! until diurnal diagn. are fixed, nssw should be even

&&END_PARAMETERS

&INPUTZ
 YEARI=0001,MONTHI=1,DATEI=1,HOURI=0, ! pick IYEAR1=YEARI (default) or < YEARI
 YEARE=0001,MONTHE=1,DATEE=1,HOURE=1,     KDIAG=12*0,9,
 ISTART=2,IRANDI=0, YEARE=0001,MONTHE=1,DATEE=1,HOURE=1,
/

