"""D177 item 1: the zenith angle COSZ1 of every step from the clock (no recorded COSZ1).

Real code path (P2SAoM40, read-only source):
  ATM_DRV.f:220  CALL CALC_ZENITH_ANGLE(modelEclock, 1, cosz1)          every step (after DYNAM, before CONDSE); RADIA recomputes the same value
  Zenith.F90     rot1 = orbit%getHourAngle(t1), rot2 = orbit%getHourAngle(t1 + DTsrc); drot normalised to [-pi, pi); COSZT(rot1, rot2, cosz)
  shared/AbstractOrbit.F90 getMeanHourAngle: 2*pi*fraction(t/Prot - t/Porb) - hourAngleOffset ; EOT = 0 (Earth: default_EOT 'F', PlanetaryParams.F90:129)
  Earth365DayOrbit (MODEL_COM.f makeEarthOrbit: planetName Earth, variable_orb_par = 0 since the rundeck sets master_yr = 1850 with orb_par_year_bp unset
  -> master_yr/=0 -> variable_orb_par=0, orb_par_year_bp = 1950-1850 = 100 -> orbpar(1850)); Prot = 86400*365/366 s, Porb = 365 d, VE = year 1 Mar 21 12:00
  RAD_DRV.f DAILY_orbit (1542-1597): SIND/COSD at NOON of the current day (cosD = sqrt(1-sinD^2)), called at day starts
  GEOM_B.f RAD_COSZ0: cosz_init (SINJ/COSJ, area-weighted latitudes), COSZT (lines 481-880)
Everything uses exact rational arithmetic where the Fortran does (Rational_mod, continued-fraction constructor with tolerance 1e-3 s for the
time of periapsis). Transcendental functions: the Intel libimf scalar functions when available (same library as the real build), else Python math.
"""
import math
import os
import sys
from fractions import Fraction

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

PI = 3.1415926535897932
TWOPI = 2.0 * PI
RADIAN = PI / 180.0
IM, JM = 72, 46
DTSRC = 1800
SECONDS_PER_DAY = 86400
SECONDS_PER_YEAR = 365 * SECONDS_PER_DAY
IYEAR1 = 1949            # ModelE calendar year of itime 0 (restart itime 33312 = 694 days = 1950 Nov 26): checked against the dumps, see tests

# ---- libm: Intel libimf when present (like the real build), Python math otherwise
_F = {}


def _libm(use_imf=True):
    if use_imf and 'imf' not in _F:
        import ctypes
        d = os.environ.get("INTEL_LIBIMF_DIR", "/panfs/ccds02/app/modules/intel/platform/x86_64/rhel/8.6/2020Update4/"
                           "compilers_and_libraries_2020.4.304/linux/compiler/lib/intel64_lin")
        try:
            ctypes.CDLL(os.path.join(d, "libintlc.so.5"), mode=ctypes.RTLD_GLOBAL)
            lib = ctypes.CDLL(os.path.join(d, "libimf.so"))
            fn = {}
            for nm in ('sin', 'cos', 'tan', 'atan', 'atan2', 'asin', 'acos', 'sqrt', 'exp'):
                f = getattr(lib, nm)
                f.restype = ctypes.c_double
                f.argtypes = [ctypes.c_double] * (2 if nm == 'atan2' else 1)
                fn[nm] = f
            _F['imf'] = fn
        except OSError:
            _F['imf'] = None
    if use_imf and _F.get('imf'):
        return _F['imf']
    return dict(sin=math.sin, cos=math.cos, tan=math.tan, exp=math.exp, atan=math.atan, atan2=math.atan2, asin=math.asin, acos=math.acos, sqrt=math.sqrt)


def _mod(a, p):
    """Fortran MODULO for reals (result has the sign of p)."""
    r = math.fmod(a, p)
    if r != 0.0 and (r < 0.0) != (p < 0.0):
        r += p
    return r


TABL1 = (  # 47 rows, source orbpar.f (generated by script from the real file)
    (-2462.2214466, 31.609974, 251.9025),
    (-857.3232075, 32.620504, 280.8325),
    (-629.3231835, 24.172203, 128.3057),
    (-414.2804924, 31.983787, 292.7252),
    (-311.7632587, 44.828336, 15.3747),
    (308.9408604, 30.973257, 263.7951),
    (-162.5533601, 43.668246, 308.4258),
    (-116.1077911, 32.246691, 240.0099),
    (101.1189923, 30.599444, 222.9725),
    (-67.6856209, 42.681324, 268.7809),
    (24.9079067, 43.836462, 316.7998),
    (22.5811241, 47.439436, 319.6024),
    (-21.1648355, 63.219948, 143.805),
    (-15.6549876, 64.230478, 172.7351),
    (15.3936813, 1.01053, 28.93),
    (14.6660938, 7.437771, 123.5968),
    (-11.7273029, 55.782177, 20.2082),
    (10.2742696, 0.373813, 40.8226),
    (6.4914588, 13.218362, 123.4722),
    (5.8539148, 62.583231, 155.6977),
    (-5.4872205, 63.593761, 184.6277),
    (-5.4290191, 76.43831, 267.2772),
    (5.160957, 45.815258, 55.0196),
    (5.0786314, 8.448301, 152.5268),
    (-4.0735782, 56.792707, 49.1382),
    (3.7227167, 49.747842, 204.6609),
    (3.3971932, 12.058272, 56.5233),
    (-2.8347004, 75.27822, 200.3284),
    (-2.6550721, 65.241008, 201.6651),
    (-2.5717867, 64.604291, 213.5577),
    (-2.4712188, 1.647247, 17.0374),
    (2.462541, 7.811584, 164.4194),
    (2.2464112, 12.207832, 94.5422),
    (-2.0755511, 63.856665, 131.9124),
    (-1.9713669, 56.15599, 61.0309),
    (-1.8813061, 77.44884, 296.2073),
    (-1.8468785, 6.801054, 135.4894),
    (1.8186742, 62.209418, 114.875),
    (1.7601888, 20.656133, 247.0691),
    (-1.5428851, 48.344406, 256.6114),
    (1.4738838, 55.14546, 32.1008),
    (-1.4593669, 69.000539, 143.6804),
    (1.4192259, 11.07135, 16.8784),
    (-1.181898, 74.291298, 160.6835),
    (1.1756474, 11.047742, 27.5932),
    (-1.1316126, 0.636717, 348.1074),
    (1.0896928, 12.844549, 82.6496),
)
TABL4 = (  # 19 rows, source orbpar.f (generated by script from the real file)
    (0.01860798, 4.207205, 28.620089),
    (0.01627522, 7.346091, 193.788772),
    (-0.0130066, 17.857263, 308.307024),
    (0.00988829, 17.220546, 320.199637),
    (-0.003367, 16.846733, 279.376984),
    (0.00333077, 5.199079, 87.195),
    (-0.002354, 18.231076, 349.129677),
    (0.00140015, 26.216758, 128.443387),
    (0.001007, 6.359169, 154.14388),
    (0.000857, 16.210016, 291.269597),
    (0.0006499, 3.065181, 114.860583),
    (0.000599, 16.583829, 332.092251),
    (0.000378, 18.49398, 296.414411),
    (-0.000337, 6.190953, 145.76991),
    (0.000276, 18.867793, 337.237063),
    (0.000182, 17.425567, 152.092288),
    (-0.000174, 6.186001, 126.839891),
    (-0.000124, 18.417441, 210.667199),
    (1.25e-05, 0.667863, 72.108838),
)
TABL5 = (  # 78 rows, source orbpar.f (generated by script from the real file)
    (7391.022589, 31.609974, 251.9025),
    (2555.1526947, 32.620504, 280.8325),
    (2022.7629188, 24.172203, 128.3057),
    (-1973.6517951, 0.636717, 348.1074),
    (1240.2321818, 31.983787, 292.7252),
    (953.8679112, 3.138886, 165.1686),
    (-931.7537108, 30.973257, 263.7951),
    (872.3795383, 44.828336, 15.3747),
    (606.3544732, 0.991874, 58.5749),
    (-496.0274038, 0.373813, 40.8226),
    (456.9608039, 43.668246, 308.4258),
    (346.946232, 32.246691, 240.0099),
    (-305.8412902, 30.599444, 222.9725),
    (249.6173246, 2.147012, 106.5937),
    (-199.10272, 10.511172, 114.5182),
    (191.0560889, 42.681324, 268.7809),
    (-175.2936572, 13.650058, 279.6869),
    (165.9068833, 0.986922, 39.6448),
    (161.1285917, 9.874455, 126.4108),
    (139.7878093, 13.013341, 291.5795),
    (-133.5228399, 0.262904, 307.2848),
    (117.0673811, 0.004952, 18.93),
    (104.6907281, 1.142024, 273.7596),
    (95.3227476, 63.219948, 143.805),
    (86.7824524, 0.205021, 191.8927),
    (86.0857729, 2.151964, 125.5237),
    (70.5893698, 64.230478, 172.7351),
    (-69.9719343, 43.836462, 316.7998),
    (-62.5817473, 47.439436, 319.6024),
    (61.5450059, 1.384343, 69.7526),
    (-57.9364011, 7.437771, 123.5968),
    (57.1899832, 18.829299, 217.6432),
    (-57.0236109, 9.500642, 85.5882),
    (-54.2119253, 0.431696, 156.2147),
    (53.2834147, 1.16009, 66.9489),
    (52.1223575, 55.782177, 20.2082),
    (-49.0059908, 12.639528, 250.7568),
    (-48.3118757, 1.155138, 48.0188),
    (-45.4191685, 0.168216, 8.3739),
    (-42.235792, 1.647247, 17.0374),
    (-34.7971099, 10.884985, 155.3409),
    (34.4623613, 5.610937, 94.1709),
    (-33.8356643, 12.658184, 221.112),
    (33.6689362, 1.01053, 28.93),
    (-31.2521586, 1.983748, 117.1498),
    (-30.8798701, 14.023871, 320.5095),
    (28.4640769, 0.560178, 262.3602),
    (-27.1960802, 1.273434, 336.2148),
    (27.0860736, 12.021467, 233.0046),
    (-26.3437456, 62.583231, 155.6977),
    (24.725374, 63.593761, 184.6277),
    (24.6732126, 76.43831, 267.2772),
    (24.4272733, 4.28091, 78.9281),
    (24.0127327, 13.218362, 123.4722),
    (21.7150294, 17.818769, 188.7132),
    (-21.5375347, 8.359495, 180.1364),
    (18.1148363, 56.792707, 49.1382),
    (-16.9603104, 8.448301, 152.5268),
    (-16.1765215, 1.978796, 98.2198),
    (15.5567653, 8.863925, 97.4808),
    (15.4846529, 0.186365, 221.5376),
    (15.2150632, 8.996212, 168.2438),
    (14.5047426, 6.771027, 161.1199),
    (-14.3873316, 45.815258, 55.0196),
    (13.1351419, 12.002811, 262.6495),
    (12.8776311, 75.27822, 200.3284),
    (11.9867234, 65.241008, 201.6651),
    (11.9385578, 18.870667, 294.6547),
    (11.7030822, 22.009553, 99.8233),
    (11.6018181, 64.604291, 213.5577),
    (-11.2617293, 11.498094, 154.1631),
    (-10.4664199, 0.578834, 232.7153),
    (10.433397, 9.237738, 138.3034),
    (-10.2377466, 49.747842, 204.6609),
    (10.1934446, 2.147012, 106.5938),
    (-10.1280191, 1.196895, 250.4676),
    (10.0289441, 2.133898, 332.3345),
    (-10.0034259, 0.173168, 27.3039),
)


# ---------------------------------------------------------------------------------------------- orbpar (shared/orbpar.f)
def orbpar(year, use_imf=True):
    """Berger orbital parameters: (eccentricity, obliquity [deg], longitude of perihelion [deg])."""
    m = _libm(use_imf)
    sin, cos, atan2, sqrt = m['sin'], m['cos'], m['atan2'], m['sqrt']
    ym = year - 1950.0
    sumc = 0.0
    for a, b, c in TABL1:
        arg = RADIAN * (ym * b / 3600.0 + c)
        sumc = sumc + a * cos(arg)
    oblq = 23.320556 + sumc / 3600.0
    es = ec = 0.0
    for a, b, c in TABL4:
        arg = RADIAN * (ym * b / 3600.0 + c)
        es = es + a * sin(arg)
        ec = ec + a * cos(arg)
    eccen = sqrt(es * es + ec * ec)
    pie = atan2(es, ec)
    f = 0.0
    for a, b, c in TABL5:
        arg = RADIAN * (ym * b / 3600.0 + c)
        f = f + a * sin(arg)
    psi = RADIAN * (3.392506 + (ym * 50.439273 + f) / 3600.0)
    om = _mod(pie + psi + 0.5 * TWOPI, TWOPI)
    if om < 0.0:
        om = om + TWOPI
    return eccen, oblq, om / RADIAN


# ---------------------------------------------------------------------------------------------- Rational helpers
def rational_from_real(x, tol):
    """shared/Rational.F90 newRational_real_dp: continued fraction to within `tol`; returns an exact Fraction."""
    absx = abs(x)
    w = int(math.floor(absx))
    xx = absx - w
    p2, q2 = 1, 0
    p1, q1 = 0, 1
    pn, qn = 0, 1
    while xx != 0.0:
        xx = 1.0 / xx
        a = int(math.floor(xx))
        xx = xx - a
        pn = a * p1 + p2
        qn = a * q1 + q2
        p2, q2 = p1, q1
        p1, q1 = pn, qn
        if abs(qn * (absx - w) - pn) < qn * tol:
            break
    r = Fraction(w) + Fraction(pn, qn)
    return -r if x < 0 else r


def rat_real(f):
    """Rational%toReal: real(numerator)/real(denominator) + whole (whole and numerator carry the sign of the rational)."""
    whole = int(f)            # truncation toward zero
    rem = f - whole
    return float(rem.numerator) / float(rem.denominator) + float(whole)


class EarthOrbit:
    """Earth365DayOrbit for orbpar(year) parameters (see module docstring)."""

    def __init__(self, year=1850.0, use_imf=True):
        self.m = _libm(use_imf)
        self.ecc, self.obl, self.omegvp = orbpar(year, use_imf)
        self.prot = Fraction(SECONDS_PER_DAY * 365, 366)
        self.porb = Fraction(SECONDS_PER_YEAR)
        # julian calendar year 1, month 3, date 21, hour 12: 59 days elapsed before Mar 1 + 20
        self.t_ve = Fraction((59 + 20) * SECONDS_PER_DAY + 12 * 3600)
        m = self.m
        ta = -self.omegvp * RADIAN
        ma = self._mean_from_true(ta)
        self.t_peri = self.t_ve - rational_from_real(ma / TWOPI * float(self.porb), 1.0e-3)

    def _mean_from_true(self, nu):
        m, e = self.m, self.ecc
        ea = 2.0 * m['atan'](m['sqrt']((1.0 - e) / (1.0 + e)) * m['tan'](nu / 2.0))
        return ea - e * m['sin'](ea)

    def mean_anomaly(self, t):
        f = (t % self.porb) - (self.t_peri % self.porb)
        f = f / self.porb
        return rat_real(f) * TWOPI

    def true_anomaly(self, t):
        m, e = self.m, self.ecc
        ma = self.mean_anomaly(t)
        x = ma + e * (m['sin'](ma) + e * m['sin'](2.0 * ma) / 2.0)
        while True:
            f = x - e * m['sin'](x) - ma
            df = 1.0 - e * m['cos'](x)
            dx = -f / df
            x = x + dx
            if abs(dx) < 1.0e-10:
                break
        return _mod(2.0 * m['atan'](m['sqrt']((1.0 + e) / (1.0 - e)) * m['tan'](x / 2.0)), TWOPI)

    def sin_declination(self, t):
        m = self.m
        nu = self.true_anomaly(t)
        delta = nu + self.omegvp * RADIAN
        return m['sin'](self.obl * RADIAN) * m['sin'](delta)

    def hour_angle(self, t):
        """AbstractOrbit.getHourAngle with EOT = 'F' and hourAngleOffset = 0."""
        f1 = t / self.prot
        f2 = t / self.porb
        d = f1 - f2
        fr = d - (d.numerator // d.denominator)       # Rational fraction(): value in [0, 1)
        return _mod(TWOPI * rat_real(fr) - 0.0, TWOPI)


def time_of_itime(itime, iyear1=IYEAR1):
    """BaseTime (seconds since 0001-01-01 00:00 in the 365-day calendar) of the model clock at `itime` (MODELE.f:1315-1320)."""
    return Fraction((iyear1 - 1) * SECONDS_PER_YEAR + DTSRC * itime)


# ---------------------------------------------------------------------------------------------- RAD_COSZ0
class CoszGrid:
    """GEOM_B.f RAD_COSZ0: cosz_init (SINJ, COSJ), COSZT, with LON(I) = DLON*(I-.5), SINIP/COSIP."""

    def __init__(self, use_imf=True):
        m = self.m = _libm(use_imf)
        sin, cos = m['sin'], m['cos']
        dlat = (180.0 / 45.0) * RADIAN        # DLAT_DG = 180./REAL(JM-1) (REAL*4 expression, exactly 4.0); radian = pi/180
        dlon = TWOPI * (1.0 / 72.0)
        self.lon = np.array([dlon * (i - 0.5) for i in range(1, IM + 1)])
        self.sinip = np.array([sin(x) for x in self.lon])
        self.cosip = np.array([cos(x) for x in self.lon])
        sinj = np.zeros(JM + 1)
        cosj = np.zeros(JM + 1)
        phis, sphis, cphis = -0.25 * TWOPI, -1.0, 0.0
        for j in range(1, JM):                      # J_0 .. J_1S = 1 .. JM-1
            phin = dlat * (j - 0.5 * JM)
            sphin, cphin = sin(phin), cos(phin)
            phim = (phin * sphin + cphin - phis * sphis - cphis) / (sphin - sphis)
            sinj[j], cosj[j] = sin(phim), cos(phim)
            phis, sphis, cphis = phin, sphin, cphin
        phin, sphin, cphin = 0.25 * TWOPI, 1.0, 0.0
        phim = (phin * sphin + cphin - phis * sphis - cphis) / (sphin - sphis)
        sinj[JM], cosj[JM] = sin(phim), cos(phim)
        self.sinj, self.cosj = sinj, cosj

    def coszt(self, rot1, rot2, sind, cosd):
        """COSZT(rot1, rot2, cosz): time-weighted cosz, array (IM, JM); polar boxes: column I=1 only (others stay 0)."""
        m = self.m
        sin, cos, acos, sqrt = m['sin'], m['cos'], m['acos'], m['sqrt']
        zero1 = 1.0e-2
        drot = rot2 - rot1
        sr1, cr1, sr2, cr2 = sin(rot1), cos(rot1), sin(rot2), cos(rot2)
        lt1 = rot1 + self.lon
        lt2 = rot2 + self.lon
        slt1 = sr1 * self.cosip + cr1 * self.sinip
        slt2 = sr2 * self.cosip + cr2 * self.sinip
        cz = np.zeros((IM, JM + 1))
        for j in (1, JM):                            # polar boxes
            sjsd = self.sinj[j] * sind
            cjcd = self.cosj[j] * cosd
            if sjsd + cjcd > zero1:
                if sjsd - cjcd < 0.0:
                    dusk = acos(-sjsd / cjcd)
                    sdusk = sqrt(cjcd * cjcd - sjsd * sjsd) / cjcd
                    dawn, sdawn = -dusk, -sdusk
                    cz[0, j] = (sjsd * (dusk - dawn) + cjcd * (sdusk - sdawn)) / TWOPI
                else:
                    cz[0, j] = sjsd
            else:
                cz[0, j] = 0.0
        for j in range(2, JM):                       # J_0S .. J_1S
            sjsd = self.sinj[j] * sind
            cjcd = self.cosj[j] * cosd
            if sjsd + cjcd > zero1:
                if sjsd - cjcd < 0.0:
                    dusk = acos(-sjsd / cjcd)
                    sdusk = sqrt(cjcd * cjcd - sjsd * sjsd) / cjcd
                    dawn, sdawn = -dusk, -sdusk
                    zero2 = zero1 / cjcd
                    for i in range(IM):
                        if not (dusk > lt1[i] + zero2):
                            dusk = dusk + TWOPI
                            dawn = dawn + TWOPI
                        if not (dawn < lt2[i] - zero2):
                            cz[i, j] = 0.0
                            continue
                        if dawn >= lt1[i]:
                            if dusk < lt2[i]:
                                cz[i, j] = (sjsd * (dusk - dawn) + cjcd * (sdusk - sdawn)) / drot
                            else:
                                cz[i, j] = (sjsd * (lt2[i] - dawn) + cjcd * (slt2[i] - sdawn)) / drot
                            continue
                        if dusk >= lt2[i]:
                            cz[i, j] = sjsd + cjcd * (slt2[i] - slt1[i]) / drot
                            continue
                        if not (dawn + TWOPI < lt2[i] - zero2):
                            cz[i, j] = (sjsd * (dusk - lt1[i]) + cjcd * (sdusk - slt1[i])) / drot
                        else:
                            cz[i, j] = (sjsd * (lt2[i] - dawn - TWOPI + dusk - lt1[i]) + cjcd * (slt2[i] - sdawn + sdusk - slt1[i])) / drot
                else:
                    for i in range(IM):
                        cz[i, j] = sjsd + cjcd * (slt2[i] - slt1[i]) / drot
            else:
                cz[:, j] = 0.0
        return cz[:, 1:]


class Zenith:
    """cosz1(itime) for the dumps' model: orbit parameters of 1850, noon-of-day declination, DTsrc = 1800 s."""

    def __init__(self, year=1850.0, use_imf=True, iyear1=IYEAR1):
        self.orbit = EarthOrbit(year, use_imf)
        self.grid = CoszGrid(use_imf)
        self.iyear1 = iyear1
        self._daily = {}

    def daily(self, t):
        """DAILY_orbit: sinD, cosD at noon of the day containing t."""
        day0 = (t // SECONDS_PER_DAY) * SECONDS_PER_DAY
        if day0 not in self._daily:
            tn = Fraction(day0) + Fraction(SECONDS_PER_DAY, 2)
            sind = self.orbit.sin_declination(tn)
            self._daily[day0] = (sind, self.orbit.m['sqrt'](1.0 - sind ** 2))
        return self._daily[day0]

    def cosz1(self, itime, t=None):
        """CALC_ZENITH_ANGLE(modelEclock, 1, cosz1) for the clock reading `itime` (or an explicit time t)."""
        t1 = time_of_itime(itime, self.iyear1) if t is None else t
        sind, cosd = self.daily(t1)
        rot1 = self.orbit.hour_angle(t1)
        rot2 = self.orbit.hour_angle(t1 + DTSRC)
        drot = rot2 - rot1
        drot = -PI + _mod(drot + PI, 2.0 * PI)
        if abs(drot) > PI / 4:
            raise RuntimeError("Time step is too large for accurate radiation.")
        if drot < 0:
            rot2 = rot1
            rot1 = rot1 + drot
        elif drot > 0:
            rot2 = rot1 + drot
        else:
            rot2 = rot2 + 1.0e-10
        return self.grid.coszt(rot1, rot2, sind, cosd)
