#ifndef _RUNDECK_OPTS_H
#define _RUNDECK_OPTS_H

#define GISS_RAD_OFF
#define NEW_IO
#define IRRIGATION_ON
#define CHECK_OCEAN
#define CONSTANT_MESO_DIFFUSIVITY
#define OCN_LAYERING L13
#define ODIFF_FIXES_2017
#define EXPEL_COASTAL_ICEXS
#define NEW_BCdalbsn
#define CACHED_SUBDD
#endif
